/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p activeinterface /home/erin/Desktop/qt6Upgrade/botui/dbus/org.freedesktop.NetworkManager.Connection.Active.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "activeinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerConnectionActiveInterface
 */

OrgFreedesktopNetworkManagerConnectionActiveInterface::OrgFreedesktopNetworkManagerConnectionActiveInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerConnectionActiveInterface::~OrgFreedesktopNetworkManagerConnectionActiveInterface()
{
}


#include "activeinterface.moc"
