/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p connectioninterface /home/erin/Desktop/qt6Upgrade/botui/dbus/org.freedesktop.NetworkManager.Settings.Connection.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CONNECTIONINTERFACE_H
#define CONNECTIONINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.NetworkManager.Settings.Connection
 */
class OrgFreedesktopNetworkManagerSettingsConnectionInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.NetworkManager.Settings.Connection"; }

public:
    OrgFreedesktopNetworkManagerSettingsConnectionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFreedesktopNetworkManagerSettingsConnectionInterface();

    Q_PROPERTY(QString Filename READ filename)
    inline QString filename() const
    { return qvariant_cast< QString >(property("Filename")); }

    Q_PROPERTY(uint Flags READ flags)
    inline uint flags() const
    { return qvariant_cast< uint >(property("Flags")); }

    Q_PROPERTY(bool Unsaved READ unsaved)
    inline bool unsaved() const
    { return qvariant_cast< bool >(property("Unsaved")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> ClearSecrets()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("ClearSecrets"), argumentList);
    }

    inline QDBusPendingReply<> Delete()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Delete"), argumentList);
    }

    inline QDBusPendingReply<Variant(QString)> GetSecrets(const QString &setting_name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(setting_name);
        return asyncCallWithArgumentList(QStringLiteral("GetSecrets"), argumentList);
    }

    inline QDBusPendingReply<Variant(QString)> GetSettings()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetSettings"), argumentList);
    }

    inline QDBusPendingReply<> Save()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Save"), argumentList);
    }

    inline QDBusPendingReply<> Update(Variant(QString) properties)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(properties);
        return asyncCallWithArgumentList(QStringLiteral("Update"), argumentList);
    }

    inline QDBusPendingReply<Variant(QString)> Update2(Variant(QString) settings, uint flags, Variant(QString) args)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(settings) << QVariant::fromValue(flags) << QVariant::fromValue(args);
        return asyncCallWithArgumentList(QStringLiteral("Update2"), argumentList);
    }

    inline QDBusPendingReply<> UpdateUnsaved(Variant(QString) properties)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(properties);
        return asyncCallWithArgumentList(QStringLiteral("UpdateUnsaved"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Removed();
    void Updated();
};

namespace org {
  namespace freedesktop {
    namespace NetworkManager {
      namespace Settings {
        typedef ::OrgFreedesktopNetworkManagerSettingsConnectionInterface Connection;
      }
    }
  }
}
#endif
