/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c Serial -p Serial -N -i NetworkManagerConnection.h org.kipr.Serial.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SERIAL_H_1359245779
#define SERIAL_H_1359245779

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "NetworkManagerConnection.h"

/*
 * Proxy class for interface org.kipr.Serial
 */
class Serial: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kipr.Serial"; }

public:
    Serial(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~Serial();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void Run(const QString &path);
};

#endif
